#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "primer.name" . }}-post-init
  namespace: {{ .Release.Namespace }}
  {{- if .Values.primerNode.helmHook }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": "before-hook-creation"
  {{- end }}
spec:
  template:
    metadata:
      name: {{ template "primer.name" . }}-post-init
      {{- if .Values.primerNode.podAnnotations }}
      annotations: {{- toYaml .Values.primerNode.podAnnotations | nindent 8 }}
      {{- end }}
    spec:
      {{- if or (.Values.serviceAccount.create) (.Values.serviceAccountName) }}
      serviceAccountName: {{ template "primer.serviceAccountName" . }}
      {{- end }}
      securityContext:
        runAsUser: {{ .Values.runAsUser }}
        {{- if .Values.primerNode.podSecurityContext }}
          {{- toYaml .Values.primerNode.podSecurityContext | nindent 8 }}
        {{- end }}
      {{- if .Values.primerNode.initContainers }}
      initContainers: {{-  tpl (toYaml .Values.primerNode.initContainers) . | nindent 6 }}
      {{- end }}
      containers:
      - name: {{ template "primer.name" . }}-init
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        {{- if or .Values.extraEnv .Values.extraEnvRaw }}
        env:
          {{- range $key, $value := .Values.extraEnv }}
          - name: {{ $key | quote }}
            value: {{ $value | quote }}
          {{- end }}
          {{- if .Values.extraEnvRaw }}
            {{- toYaml .Values.extraEnvRaw | nindent 10 }}
          {{- end }}
        {{- end }}
        envFrom:
          - secretRef:
              name: {{ tpl .Values.envFromSecret . }}
          {{- range .Values.envFromSecrets }}
          - secretRef:
              name: {{ tpl . $ }}
          {{- end }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- if .Values.primerNode.containerSecurityContext }}
        securityContext: {{- toYaml .Values.primerNode.containerSecurityContext | nindent 12 }}
        {{- end }}
        volumeMounts:
          - name:  config
            mountPath: {{ .Values.configMountPath | quote }}
            readOnly: true
          {{- if .Values.extraConfigs }}
          - name:  primer-extra-config
            mountPath: {{ .Values.extraConfigMountPath | quote }}
            readOnly: true
          {{- end }}
          {{- if .Values.resourcesConfigSecrets }}
          - name:  primer-resources-config
            mountPath: {{ .Values.resourceConfigMountPath | quote }}
            readOnly: true
          {{- end }}
          {{- with .Values.extraVolumeMounts }}
            {{- tpl (toYaml .) $ | nindent 10 -}}
          {{- end }}
        command: {{  tpl (toJson .Values.primerNode.command) . }}
        resources: {{- toYaml .Values.primerNode.resources | nindent 10 }}
      {{- with .Values.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if or .Values.affinity .Values.primerNode.affinity }}
      affinity:
        {{- with .Values.affinity }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.primerNode.affinity }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- if or .Values.topologySpreadConstraints .Values.primerNode.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- with .Values.topologySpreadConstraints }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.primerNode.topologySpreadConstraints }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets: {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          secret:
            secretName: {{ tpl .Values.configFromSecret . }}
        {{- if .Values.extraConfigs }}
        - name:  primer-extra-config
          configMap:
            name: {{ template "primer.fullname" . }}-extra-config
        {{- end }}
        {{- if .Values.resourcesConfigSecrets }}
        - name:  primer-resources-config
          secret:
            secretName: {{ template "primer.fullname" . }}-resources-config
        {{- end }}
        {{- with .Values.extraVolumes }}
          {{- tpl (toYaml .) $ | nindent 8 -}}
        {{- end }}
      restartPolicy: Never
