#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "primer.fullname" . }}-env
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "primer.fullname" . }}
    chart: {{ template "primer.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
stringData:
    DASHBOARD_API_PROTOCOL: {{ .Values.dashboardAPI.protocol | quote }}
    DASHBOARD_API_HOST: {{ .Values.dashboardAPI.host | quote }}
    DASHBOARD_API_PORT: {{ .Values.dashboardAPI.port | quote }}
    API_USERNAME: {{ .Values.dashboardAPI.username | quote }}
    API_PASSWORD: {{ .Values.dashboardAPI.password | quote }}
    WAIT_FOR_API_TIMEOUT: {{ .Values.dashboardAPI.waitForAPITimeout | quote }}
    {{- if .Values.extraSecretEnv }}
    {{- range $key, $value := .Values.extraSecretEnv }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
